In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
dataset=pd.read_csv("50_Startups.csv")

In [4]:
dataset

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156994.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.85        311613.28    New York  152211.77
9    94657.16       145077.58        282574.31    New York  125370.37
10   91749.16       114175.79        294919.57     Florida  124266.90
11   86419.70       153514.11             0.00    New York  122776.86
12   76253.86       113867.30        298664.47  California  118474.03
13   78389.47       153773.43        299737.29    New York  111313.02
14   73994.56       122782.75        303319.26     Florida  110352.25
15   67532.53       105751.03        304768.73     Florida  108733.99
16   94657.16       145077.58        282574.31    New York  125370.37
17   91749.16       114175.79        294919.57     Florida  124266.90
18   86419.70       153514.11             0.00    New York  122776.86
19   76253.86       113867.30        298664.47  California  118474.03
20   78389.47       153773.43        299737.29    New York  111313.02
21   73994.56       122782.75        303319.26     Florida  110352.25
22   67532.53       105751.03        304768.73     Florida  108733.99
23   77044.01        99281.34        140574.81    New York  108552.04
24   64664.71       139553.16        137962.62  California  107404.34
25   75328.87       144135.98        134050.07     Florida  105733.54

In [5]:
dataset=pd.get_dummies(dataset,dtype=int ,drop_first=True)
dataset

,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,165349.20,136897.80,471784.10,192261.83,0,1
1,162597.70,151377.59,443898.53,191792.06,0,0
2,153441.51,101145.55,407934.54,191050.39,1,0
3,144372.41,118671.85,383199.62,182901.99,0,1
4,142107.34,91391.77,366168.42,166187.94,1,0
5,131876.90,99814.71,362861.36,156994.12,0,1
6,134615.46,147198.87,127716.82,156122.51,0,0
7,130298.13,145530.06,323876.68,155752.60,1,0
8,120542.52,148718.85,311613.28,152211.77,0,1
9,94657.16,145077.58,282574.31,125370.37,0,1
10,91749.16,114175.79,294919.57,124266.90,1,0
11,86419.70,153514.11,0.00,122776.86,0,1
12,76253.86,113867.30,298664.47,118474.03,0,0
13,78389.47,153773.43,299737.29,111313.02,0,1
14,73994.56,122782.75,303319.26,110352.25,1,0
15,67532.53,105751.03,304768.73,108733.99,1,0
16,94657.16,145077.58,282574.31,125370.37,0,1
17,91749.16,114175.79,294919.57,124266.90,1,0
18,86419.70,153514.11,0.00,122776.86,0,1
19,76253.86,113867.30,298664.47,118474.03,0,0
20,78389.47,153773.43,299737.29,111313.02,0,1
21,73994.56,122782.75,303319.26,110352.25,1,0
22,67532.53,105751.03,304768.73,108733.99,1,0
23,77044.01,99281.34,140574.81,108552.04,0,1
24,64664.71,139553.16,137962.62,107404.34,0,0
25,75328.87,144135.98,134050.07,105733.54,1,0

In [6]:
dataset.columns

Index(['R&D Spend', 'Administration', 'Marketing Spend', 'Profit',
       'State_Florida', 'State_New York'],
      dtype='object')

In [7]:
Independent=dataset[['R&D Spend', 'Administration', 'Marketing Spend',
       'State_Florida', 'State_New York']]

In [8]:
Independent

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0   165349.20       136897.80        471784.10              0               1
1   162597.70       151377.59        443898.53              0               0
2   153441.51       101145.55        407934.54              1               0
3   144372.41       118671.85        383199.62              0               1
4   142107.34        91391.77        366168.42              1               0
5   131876.90        99814.71        362861.36              0               1
6   134615.46       147198.87        127716.82              0               0
7   130298.13       145530.06        323876.68              1               0
8   120542.52       148718.85        311613.28              0               1
9    94657.16       145077.58        282574.31              0               1
10   91749.16       114175.79        294919.57              1               0
11   86419.70       153514.11             0.00              0               1
12   76253.86       113867.30        298664.47              0               0
13   78389.47       153773.43        299737.29              0               1
14   73994.56       122782.75        303319.26              1               0
15   67532.53       105751.03        304768.73              1               0
16   94657.16       145077.58        282574.31              0               1
17   91749.16       114175.79        294919.57              1               0
18   86419.70       153514.11             0.00              0               1
19   76253.86       113867.30        298664.47              0               0
20   78389.47       153773.43        299737.29              0               1
21   73994.56       122782.75        303319.26              1               0
22   67532.53       105751.03        304768.73              1               0
23   77044.01        99281.34        140574.81              0               1
24   64664.71       139553.16        137962.62              0               0
25   75328.87       144135.98        134050.07              1               0

In [9]:
dependent=dataset[["Profit"]]

In [10]:
dependent

       Profit
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156994.12
6   156122.51
7   155752.60
8   152211.77
9   125370.37
10  124266.90
11  122776.86
12  118474.03
13  111313.02
14  110352.25
15  108733.99
16  125370.37
17  124266.90
18  122776.86
19  118474.03
20  111313.02
21  110352.25
22  108733.99
23  108552.04
24  107404.34
25  105733.54

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(Independent,dependent,test_size=0.3,random_state=0)

In [12]:
x_train

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
18   86419.70       153514.11             0.00              0               1
19   76253.86       113867.30        298664.47              0               0
16   94657.16       145077.58        282574.31              0               1
1   162597.70       151377.59        443898.53              0               0
10   91749.16       114175.79        294919.57              1               0
25   75328.87       144135.98        134050.07              1               0
24   64664.71       139553.16        137962.62              0               0
8   120542.52       148718.85        311613.28              0               1
6   134615.46       147198.87        127716.82              0               0
4   142107.34        91391.77        366168.42              1               0
9    94657.16       145077.58        282574.31              0               1
7   130298.13       145530.06        323876.68              1               0
23   77044.01        99281.34        140574.81              0               1
3   144372.41       118671.85        383199.62              0               1
0   165349.20       136897.80        471784.10              0               1
21   73994.56       122782.75        303319.26              1               0
15   67532.53       105751.03        304768.73              1               0
12   76253.86       113867.30        298664.47              0               0

In [13]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import GridSearchCV
param_grid={'n_estimators':[100,50],'criterion':['friedman_mse','squared_error','absolute_error','poisson']}
grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(x_train,y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

C:\Users\SPPSS\anaconda3\Lib\site-packages\sklearn\base.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['friedman_mse', 'squared_error',
                                       'absolute_error', 'poisson'],
                         'n_estimators': [100, 50]},
             verbose=3)

In [14]:
re=grid.cv_results_
print('R_score value for the best parameter{}:'.format(grid.best_params_))

R_score value for the best parameter{'criterion': 'poisson', 'n_estimators': 50}:

In [16]:
table=pd.DataFrame.from_dict(re)

In [17]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.698611,0.060721,0.050382,0.002751,friedman_mse,100,"{'criterion': 'friedman_mse', 'n_estimators': ...",0.948944,0.712363,0.685459,0.793255,-0.242200,0.579564,0.421011,4
1,0.376920,0.006858,0.038444,0.009945,friedman_mse,50,"{'criterion': 'friedman_mse', 'n_estimators': 50}",0.947608,0.755096,0.645995,0.691545,-0.335828,0.540883,0.450263,5
2,0.722254,0.053365,0.056194,0.008605,squared_error,100,"{'criterion': 'squared_error', 'n_estimators':...",0.951898,0.726468,0.850560,0.664554,-0.715061,0.495684,0.613474,6
3,0.317201,0.032349,0.034789,0.004751,squared_error,50,"{'criterion': 'squared_error', 'n_estimators':...",0.922168,0.758371,0.739068,0.656365,-0.104488,0.594297,0.359870,3
4,0.629794,0.025777,0.045099,0.006403,absolute_error,100,"{'criterion': 'absolute_error', 'n_estimators'...",0.946112,0.706617,0.879185,0.768530,-1.410140,0.378061,0.897985,8
5,0.345234,0.029164,0.031066,0.001702,absolute_error,50,"{'criterion': 'absolute_error', 'n_estimators'...",0.970857,0.730872,0.814697,0.771937,-1.241801,0.409312,0.829547,7
6,0.701165,0.020370,0.055953,0.012338,poisson,100,"{'criterion': 'poisson', 'n_estimators': 100}",0.957930,0.789221,0.756156,0.701644,-0.217645,0.597461,0.416448,2
7,0.373548,0.030050,0.041108,0.008857,poisson,50,"{'criterion': 'poisson', 'n_estimators': 50}",0.956185,0.694917,0.802209,0.749369,-0.021370,0.636262,0.340177,1

In [18]:
RD_Spend_input = float(input("R&D_Spend: "))
Administration_input = float(input("Administration: "))
Marketing_Spend_input = float(input("Marketing_Spend: "))
State_Florida_input=int(input("State_Florida 0 or 1:"))
State_New_York_input=int(input("State_New York yes 0 or 1:"))

R&D_Spend:  15000
Administration:  25000
Marketing_Spend:  35000
State_Florida 0 or 1: 0
State_New York yes 0 or 1: 0

In [19]:
Future_Prediction=grid.predict([[RD_Spend_input,Administration_input,Marketing_Spend_input,State_Florida_input,State_New_York_input]])
print("Future_Prediction {}:".format(Future_Prediction))

Future_Prediction [108996.9662]:

C:\Users\SPPSS\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(